# syntax=docker/dockerfile:1

FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine

# SPA nginx config
COPY deploy/nginx-web.conf /etc/nginx/conf.d/default.conf

# Statika
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
